using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace InventorySystem.Models
{
    public class Item
    {
        [Key]
        public Guid Id { get; set; } = Guid.NewGuid();
        [Required]
        public Guid InventoryId { get; set; }
        [ForeignKey("InventoryId")]
        public Inventory? Inventory { get; set; }

        // Custom identifier generated by CustomIdService (unique per inventory)
        [Required]
        public string CustomId { get; set; } = string.Empty;

        [Required]
        public string Name { get; set; } = string.Empty;

        // JSON payload for custom fields (flexible template fields)
        public string? CustomFieldsJson { get; set; }

        // Optimistic locking
        [Timestamp]
        public byte[]? RowVersion { get; set; }

        public ICollection<Comment>? Comments { get; set; }
        public ICollection<ItemLike>? Likes { get; set; }
    }
}
